name: Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    if: $(( "!startsWith(github.event.head_commit.message, 'docs: ')" && "!startsWith(github.event.head_commit.message, 'readme: ')" && "!startsWith(github.event.head_commit.message, 'workflow: ')" ))
    runs-on: ubuntu-latest
    steps:

      - name: clone repo
        run: git clone https://github.com/alemontn/alcochive.git ~/alcochive

      - name: make debian package
        run: |
          mkdir ~/out ~/log
          cd ~/alcochive
          ./scripts/package.sh deb
          mv build/out/*.deb ~/out/alcochive.deb
          cp build/*.log ~/log

      - name: install alcochive
        run: sudo dpkg -i ~/out/alcochive.deb

      - name: make fedora package
        run: |
          cd ~/alcochive
          sudo rm -rf build
          ./scripts/package.sh rpm
          mv build/out/*.rpm ~/out
          cp build/*.log ~/log

      - name: make bundle
        run: |
          cd ~/alcochive
          sudo rm -rf build
          ./scripts/package.sh bundle
          mv build/out/alcochive.bundle ~/out
          mv build/out/alcochive.alzr ~/out
          cp build/*.log ~/log

      - name: upload logs
        if: always()
        run: |
          cd ~/alcochive/build
          for logFile in *.log ~/log/*
          do
            echo ":: $logFile:"
            cat "$logFile" >&2
          done

      - name: upload packages
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ~/out
