name: package

on:
  push:
    paths:
      - alar.sh
      - package.conf
      - compress.d/**
      - scripts/**
      - .github/workflows/package.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        run: git clone https://github.com/alemontn/alcochive.git ~/alcochive

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install pacman-package-manager

      - name: generate package specs
        run: |
          cd ~/alcochive
          ./scripts/spec.sh

      - name: make debian package
        run: |
          mkdir ~/out ~/log
          cd ~/alcochive
          ./scripts/package.sh deb
          mv build/out/*.deb ~/out/alcochive.deb
          cp build/*.log ~/log

      - name: install alcochive
        run: sudo dpkg -i ~/out/alcochive.deb

      - name: make fedora package
        run: |
          cd ~/alcochive
          ./scripts/package.sh rpm
          mv build/out/*.rpm ~/out/alcochive.rpm
          cp build/*.log ~/log

      - name: make arch package
        run: |
          cd ~/alcochive
          ./scripts/package.sh arch
          mv build/out/*.pkg.tar.zst ~/out/alcochive.pkg.tar.zst
          cp build/*.log ~/log

      - name: make bundle
        run: |
          cd ~/alcochive
          ./scripts/package.sh bundle
          mv build/out/* ~/out
          cp build/*.log ~/log

      - name: upload logs
        if: always()
        run: |
          cd ~/alcochive/build
          for logFile in *.log ~/log/*
          do
            echo ":: $logFile:"
            cat "$logFile" >&2
          done

      - name: upload packages
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ~/out
