name: Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: clone repo
        run: git clone https://github.com/alemontn/alcochive.git ~/alcochive

      - name: make debian package
        run: |
          mkdir ~/out
          cd ~/alcochive
          ./scripts/package.sh deb
          mv build/out/*.deb ~/out/alcochive.deb

      - name: make bundle
        run: |
          cd ~/alcochive
          sudo rm -rf build
          ./scripts/package.sh bundle
          mv build/out/alcochive.bundle ~/out

      - name: upload logs
        if: $(( always() && contains(needs.*.result, 'failure') ))
        run: |
          cd ~/alcochive/build
          for logFile in *.log
          do
            echo ":: $logFile:"
            cat "$logFile" >&2
          done

      - name: upload packages
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ~/out
